var providers = {
  1: { "name": "John Clarke",
       "solution-orientation": 6,
       "structured": 6,
       "active": 8,
       "practical": 4,
       "self-disclosure": 9,
       "gender": "Male",
       "birth_year": 1988,
       "ethnicity": "White",
       "sexual_orientation": "Straight",
       "locations": ["Noe Valley"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Coaching"],
       "days": ["Tuesday","Wednesday"],
       "times": ["Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

  2: { "name": "Sadie Phillips",
       "solution-orientation": 6,
       "structured": 5,
       "active": 8,
       "practical": 8,
       "self-disclosure": 7,
       "gender": "Female",
       "birth_year": 1983,
       "ethnicity": "White",
       "sexual_orientation": "Straight",
       "locations": ["Pacific Heights"],
       "therapies": ["Cognitive Behavioral Therapy","Interpersonal Therapy","Eclecticism","Clinical Health Psychology"],
       "days": ["Monday","Wednesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

  3: { "name": "Neil Howell",
       "solution-orientation": 8,
       "structured": 8,
       "active": 8,
       "practical": 7,
       "self-disclosure": 7,
       "gender": "Male",
       "birth_year": 1963,
       "ethnicity": "White",
       "sexual_orientation": "Bisexual",
       "locations": ["Pacific Heights"],
       "therapies": ["Cognitive Behavioral Therapy","Interpersonal Therapy","Coaching"],
       "days": ["Thursday","Saturday (limited)","Sunday (limited)"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   4: {"name": "Ashley Crouch",
       "solution-orientation":7,
       "structured":6,
       "active":9,
       "practical":10,
       "self-disclosure":7,
       "gender":"Female",
       "birth_year":1983,
       "ethnicity":"White",
       "sexual_orientation":"Straight",
       "locations": ["Hayes Valley/Lower Haight/Duboce Triangle"],
       "therapies": ["Psychodynamic","Humanistic","Mindfulness/Meditation"],
       "days": ["Monday","Wednesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   5:  {"name": "Emily Mills",
        "solution-orientation":4,
   	"structured":2,
   	"active":6,
   	"practical":5,
   	"self-disclosure":1,
   	"gender":"Female",
   	"birth_year":1982,
   	"ethnicity":"White",
   	"sexual_orientation":"Gay/Lesbian",
   	"locations": ["Pacific Heights"],
       "therapies": ["Psychodynamic","Interpersonal Therapy","Mindfulness/Meditation"],
       "days": ["Monday","Wednesday","Friday","Saturday (limited)"],
       "times": ["Evening (5pm - 8pm)"]},

   6:  {"name": "Rochelle Greenhagen",
       "solution-orientation":3,
   	"structured":1,
   	"active":7,
   	"practical":9,
   	"self-disclosure":5,
   	"gender":"Female",
   	"birth_year":1984,
   	"ethnicity":"White",
   	"sexual_orientation":"Straight",
   	"locations": ["Marina/Cow Hollow"],
       "therapies": ["Psychodynamic","Humanistic","Relational"],
       "days": ["Tuesday","Wednesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   7:     {"name": "Adam Snow",
       "solution-orientation":5,
   	"structured":1,
   	"active":5,
   	"practical":6,
   	"self-disclosure":2,
   	"gender":"Male",
   	"birth_year":1982,
   	"ethnicity":"White",
   	"sexual_orientation":"Bisexual",
   	"locations": ["Hayes Valley/Lower Haight/Duboce Triangle"],
       "therapies": ["Psychodynamic","Humanistic","Interpersonal Therapy"],
       "days": ["Monday","Thursday","Saturday (limited)"],
       "times": ["Mornings (7am - 11am)","Evening (5pm - 8pm)"]},

   8:     {"name": "Sarah Soul",
       "solution-orientation":3,
   	"structured":5,
   	"active":8,
   	"practical":10,
   	"self-disclosure":0,
   	"gender":"Female",
   	"birth_year":1976,
   	"ethnicity":"White",
   	"sexual_orientation":"Gay/lesbian",
   	"locations": ["Castro/Twin Peaks"],
       "therapies": ["Psychodynamic","Humanistic","Cognitive Behavioral Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Monday","Tuesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)"]},

   9:     {"name": "Bradford Smallwood",
       "solution-orientation":7,
   	"structured":4,
   	"active":8,
   	"practical":10,
   	"self-disclosure":3,
   	"gender":"Male",
   	"birth_year":1979,
   	"ethnicity":"White",
   	"sexual_orientation":"Straight",
   	"locations": ["Marina/Cow Hollow"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy"],
       "days": ["Tuesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   10:    {"name": "Diane DuBois",
       "solution-orientation":8,
   "structured":6,
   "active":8,
   "practical":10,
   "self-disclosure":5,
   "gender":"Female",
   "birth_year":1958,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Pacific Heights"],
       "therapies": ["Psychodynamic","Humanistic","Cognitive Behavioral Therapy","Interpersonal Therapy","Coaching"],
       "days": ["Tuesday","Thursday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   11:    {"name": "Beth Cassel",
       "solution-orientation":4,
   "structured":3,
   "active":7,
   "practical":8,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1958,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["RichMondayd"],
       "therapies": ["Psychodynamic","Humanistic","Mindfulness/Meditation"],
       "days": ["Tuesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   12:    {"name": "Holly Greenberg",
       "solution-orientation":5,
   "structured":0,
   "active":7,
   "practical":9,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1970,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Pacific Heights"],
       "therapies": ["Psychoanalytical","Psychodynamic","Somatic Therapy"],
       "days": ["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday (limited)","Sunday (limited)"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   13:    {"name": "Erika Gimbel",
       "solution-orientation":6,
   "structured":3,
   "active":8,
   "practical":9,
   "self-disclosure":6,
   "gender":"Female",
   "birth_year":1970,
   "ethnicity":"White",
   "sexual_orientation":"Unknown",
   "locations": ["Pacific Heights","East Bay/Berkeley"],
       "therapies": ["Experiential Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Monday","Tuesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   14:    {"name": "Andrea Crapanzano",
       "solution-orientation":4,
   "structured":3,
   "active":5,
   "practical":3,
   "self-disclosure":1,
   "gender":"Male",
   "birth_year":1979,
   "ethnicity":"Unknown",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Hayes Valley/Lower Haight/Duboce Triangle"],
       "therapies": ["Psychoanalytical","Psychodynamic","Interpersonal Therapy"],
       "days": ["Friday"],
       "times": ["Afternoon (2pm - 5pm)"]},

   15:    {"name": "Michael Milazzo",
       "solution-orientation":7,
   "structured":6,
   "active":8,
   "practical":8,
   "self-disclosure":5,
   "gender":"Male",
   "birth_year":1973,
   "ethnicity":"White",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Financial District","Castro/Twin Peaks"],
       "therapies": ["Cognitive Behavioral Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Wednesday","Thursday","Saturday (limited)"],
       "times": ["Afternoon (2pm - 5pm)"]},

   16:    {"name": "Warren Miller",
       "solution-orientation":7,
   "structured":3,
   "active":8,
   "practical":10,
   "self-disclosure":3,
   "gender":"Male",
   "birth_year":1969,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District"],
       "therapies": ["Psychodynamic","Humanistic","Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy","Eclecticism","Mindfulness/Meditation"],
       "days": ["Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   17:    {"name": "Aaron Hagaman",
       "solution-orientation":7,
   "structured":6,
   "active":8,
   "practical":3,
   "self-disclosure":5,
   "gender":"Male",
   "birth_year":1980,
   "ethnicity":"White",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Hayes Valley/Lower Haight/Duboce Triangle","Castro/Twin Peaks"],
       "therapies": ["Experiential Therapy","Somatic Therapy"],
       "days": ["Tuesday","Wednesday","Thursday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   18:    {"name": "Manami Yamamoto",
       "solution-orientation":5,
   "structured":7,
   "active":5,
   "practical":9,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1979,
   "ethnicity":"Asian or Pacific Islander",
   "sexual_orientation":"Straight",
   "locations": ["East Bay/Berkeley","South Bay","Laurel Heights"],
       "therapies": ["Jungian Psychotherapy","Humanistic","Cognitive Behavioral Therapy","Mindfulness/Meditation","Coaching","Existential Therapy","Expressive Arts Therapy"],
       "days": ["Monday","Tuesday","Wednesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   19:    {"name": "Gabriel Thibaut de Maisieres",
       "solution-orientation":5,
   "structured":3,
   "active":7,
   "practical":7,
   "self-disclosure":2,
   "gender":"Male",
   "birth_year":1965,
   "ethnicity":"Unknown",
   "sexual_orientation":"Unknown",
   "locations": ["Financial District","Union Square/Mid-Market"],
       "therapies": ["Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy","Coaching","Psychodrama"],
       "days": ["Wednesday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   20:    {"name": "Stacey McGuirl",
       "solution-orientation":5,
   "structured":3,
   "active":7,
   "practical":5,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1980,
   "ethnicity":"White",
   "sexual_orientation":"Bisexual",
   "locations": ["Financial District","SoMa"],
       "therapies": ["Psychoanalytical","Cognitive Behavioral Therapy","Coaching"],
       "days": ["Monday","Wednesday","Saturday (limited)"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   21:    {"name": "Tess Brigham",
       "solution-orientation":9,
   "structured":5,
   "active":9,
   "practical":10,
   "self-disclosure":8,
   "gender":"Female",
   "birth_year":1973,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District","East Bay/Berkeley"],
       "therapies": ["Cognitive Behavioral Therapy","Coaching"],
       "days": ["Wednesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   22:    {"name": "Hillary Dupuis",
       "solution-orientation":8,
   "structured":5,
   "active":8,
   "practical":10,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1972,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Mindfulness/Meditation"],
       "days": ["Wednesday","Thursday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   23:    {"name": "Jessica Harvey",
       "solution-orientation":7,
   "structured":2,
   "active":8,
   "practical":10,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1981,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District","Marina/Cow Hollow"],
       "therapies": ["Humanistic","Interpersonal Therapy","Eclecticism"],
       "days": ["Monday","Thursday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   24:    {"name": "Alicia Stephen",
       "solution-orientation":4,
   "structured":4,
   "active":8,
   "practical":7,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1988,
   "ethnicity":"Asian or Pacific Islander",
   "sexual_orientation":"Pansexual",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy","Coaching","Drama Therapy And Arts Therapy"],
       "days": ["Tuesday","Wednesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   25:    {"name": "Jo Anna Costa",
       "solution-orientation":7,
   "structured":6,
   "active":8,
   "practical":10,
   "self-disclosure":6,
   "gender":"Female",
   "birth_year":1975,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Peninsula"],
       "therapies": ["Cognitive Behavioral Therapy","Eclecticism","Coaching","Solution Focused"],
       "days": ["Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   26:    {"name": "Barbara Lankamp-Kochis",
       "solution-orientation":9,
   "structured":8,
   "active":10,
   "practical":10,
   "self-disclosure":7,
   "gender":"Female",
   "birth_year":1984,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Martinez"],
       "therapies": ["Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy"],
       "days": ["Monday","Tuesday","Wednesday","Thursday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   27:    {"name": "Jennifer Normoyle",
       "solution-orientation":8,
   "structured":3,
   "active":6,
   "practical":7,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1986,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Interpersonal Therapy"],
        "days": ["Wednesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   28:    {"name": "Natasha Collins",
       "solution-orientation":7,
   "structured":5,
   "active":7,
   "practical":8,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1976,
   "ethnicity":"Multiracial",
   "sexual_orientation":"Straight",
   "locations": ["Financial District"],
       "therapies": ["Cognitive Behavioral Therapy"],
       "days": ["Saturday (limited)"],
       "times": ["Mornings (7am - 11am)"]},

   29:    {"name": "Senna Osby",
       "solution-orientation":5,
   "structured":0,
   "active":5,
   "practical":10,
   "self-disclosure":0,
   "gender":"Female","birth_year":1976,
   "ethnicity":"Black or African American",
   "sexual_orientation":"Straight",
   "locations": ["Lower Pacific Heights"],
       "therapies": ["Psychodynamic","Eclecticism","Person-Centered Therapy"],
       "days": ["Tuesday","Saturday (limited)"],
       "times": ["Mornings (7am - 11am)","Evening (5pm - 8pm)"]},

   30:    {"name": "Lori Fink",
       "solution-orientation":6,
   "structured":3,
   "active":8,
   "practical":8,"self-disclosure":6,
   "gender":"Female",
   "birth_year":1972,
   "ethnicity":"White",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Psychodynamic","Cognitive Behavioral Therapy","Eclecticism","Mindfulness/Meditation","AEDP"],
        "days": ["Wednesday","Thursday"],
       "times": ["Midday (11am - 2pm)","Evening (5pm - 8pm)"]},

   31:    {"name": "Amy Swart",
       "solution-orientation":5,
   "structured":3,
   "active":5,
   "practical":7,
   "self-disclosure":5,
   "gender":"Female",
   "birth_year":1985,
   "ethnicity":"Multiracial",
   "sexual_orientation":"Straight",
   "locations": ["Financial District","Union Square/Mid-Market"],
       "therapies": ["Humanistic","Interpersonal Therapy","Mindfulness/Meditation"],
       "days": ["Tuesday","Thursday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   32:    {"name": "Liz Michaud",
       "solution-orientation":5,
   "structured":5,
   "active":5,
   "practical":8,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1985,
   "ethnicity":"White",
   "sexual_orientation":"Questioning/other",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Psychodynamic","Humanistic","Gestalt"],
       "days": ["Friday","Saturday (limited)"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   33:    {"name": "Clark Hsu",
       "solution-orientation":3,
   "structured":4,
   "active":7,
   "practical":8,
   "self-disclosure":5,
   "gender":"Male",
   "birth_year":1989,
   "ethnicity":"Asian or Pacific Islander",
   "sexual_orientation":"Straight",
   "locations": ["Mission/Dolores/Bernal Heights"],
       "therapies": ["Humanistic","Mindfulness/Meditation"],
       "days": ["Wednesday"],
       "times": ["Mornings (7am - 11am)"]},

   34:    {"name": "Talia Recht",
       "solution-orientation":5,
   "structured":4,
   "active":9,
   "practical":9,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1987,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District"],
       "therapies": ["Psychodynamic","Cognitive Behavioral Therapy","Eclecticism"],
       "days": ["Monday","Tuesday","Wednesday","Thursday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   35:    {"name": "Zeynep Kagan",
       "solution-orientation":5,
   "structured":5,
   "active":7,
   "practical":7,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1982,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Hayes Valley/Lower Haight/Duboce Triangle","Castro/Twin Peaks"],
       "therapies": ["Psychodynamic","Humanistic","Interpersonal Therapy"],
       "days": ["Monday","Tuesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

   36:    {"name": "Giancarlo Scherillo",
       "solution-orientation":4,
   "structured":2,
   "active":5,
   "practical":8,
   "self-disclosure":2,
   "gender":"Male",
   "birth_year":1984,
   "ethnicity":"Multiracial",
   "sexual_orientation":"Straight",
   "locations": ["RichMondayd"],
       "therapies": ["Psychodynamic","Mindfulness/Meditation"],
       "days": ["Tuesday","Thursday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   37:    {"name": "Emily Adams",
       "solution-orientation":5,
   "structured":3,
   "active":6,
   "practical":8,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1989,
   "ethnicity":"White",
   "sexual_orientation":"Questioning/other",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Psychodynamic","Humanistic","Interpersonal Therapy","Mindfulness/Meditation"],
       "days": ["Monday","Tuesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   38:    {"name": "Cosmin Gheorghe",
       "solution-orientation":10,
   "structured":7,
   "active":10,
   "practical":10,
   "self-disclosure":3,
   "gender":"Male",
   "birth_year":1974,
   "ethnicity":"Multiracial",
   "sexual_orientation":"Straight",
   "locations": ["Financial District"],
       "therapies": ["Cognitive Behavioral Therapy","Eclecticism","Coaching"],
       "days": ["Tuesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   39:    {"name": "Chip Murray",
       "solution-orientation":7,
   "structured":3,
   "active":8,
   "practical":9,
   "self-disclosure":3,
   "gender":"Male",
   "birth_year":1966,
   "ethnicity":"White",
   "sexual_orientation":"Unknown",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Psychodynamic","Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy","Eclecticism"],
       "days": ["Tuesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)"]},

   40:    {"name": "Dimitra Farmas",
       "solution-orientation":8,
   "structured":3,
   "active":6,
   "practical":9,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1978,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Castro/Twin Peaks"],
       "therapies": ["Cognitive Behavioral Therapy","Interpersonal Therapy","Mindfulness/Meditation"],
       "days": ["Monday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

   41:    {"name": "Elizabeth Heuser",
       "solution-orientation":4,
   "structured":3,
   "active":5,
   "practical":7,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1978,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District"],
       "therapies": ["Humanistic","Mindfulness/Meditation"],
       "days": ["Saturday (limited)"],
       "times": ["Mornings (7am - 11am)","Evening (5pm - 8pm)"]},

   42:    {"name": "Chia Ning (Michelle) Chang",
       "solution-orientation":7,
   "structured":3,
   "active":7,
   "practical":7,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1988,
   "ethnicity":"Asian or Pacific Islander",
   "sexual_orientation":"Bisexual",
   "locations": ["Noe Valley"],
       "therapies": ["Psychodynamic","Experiential Therapy","Coaching","Strategic Family Therapy"],
       "days": ["Wednesday","Thursday","Sunday (limited)"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)"]},

   43:    {"name": "Madhu Batheja",
       "solution-orientation":6,
   "structured":1,
   "active":8,
   "practical":9,
   "self-disclosure":1,
   "gender":"Female",
   "birth_year":1951,
   "ethnicity":"Unknown",
   "sexual_orientation":"Unknown",
   "locations": ["Pacific Heights"],
       "therapies": ["Psychodynamic","Eclecticism","Somatic Therapy"],
       "days": ["Tuesday","Wednesday","Thursday"],
       "times": ["Afternoon (2pm - 5pm)"]},

   44:    {"name": "Holly Micheletos",
       "solution-orientation":6,
   "structured":5,
   "active":7,
   "practical":9,
   "self-disclosure":1,
   "gender":"Female",
   "birth_year":1966,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["RichMondayd"],
       "therapies": ["Psychodynamic","Cognitive Behavioral Therapy","Interpersonal Therapy"],
       "days": ["Monday","Tuesday","Wednesday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

45:    {"name": "Nadia Ashjaee",
       "solution-orientation":7,
   "structured":7,
   "active":7,
   "practical":8,
   "self-disclosure":6,
   "gender":"Female",
   "birth_year":1980,
   "ethnicity":"Middle Eastern or North African",
   "sexual_orientation":"Straight",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Interpersonal Therapy","Experiential Therapy"],
       "days": ["Monday","Tuesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

46:    {"name": "Kip Williams",
       "solution-orientation":5,
   "structured":2,
   "active":7,
   "practical":3,
   "self-disclosure":7,
   "gender":"Male",
   "birth_year":1982,
   "ethnicity":"White",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Civic Center"],
       "therapies": ["Humanistic","Mindfulness/Meditation","Acceptance And Commitment Therapy"],
       "days": ["Tuesday"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

47:    {"name": "Tracy McGillis",
       "solution-orientation":6,
   "structured":4,
   "active":8,
   "practical":9,
   "self-disclosure":5,
   "gender":"Female",
   "birth_year":1974,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Interpersonal Therapy","Eclecticism","Mindfulness/Meditation","Coaching"],
       "days": ["Wednesday","Thursday","Friday"],
       "times": ["Mornings (7am - 11am)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

48:    {"name": "Lauren Korshak",
       "solution-orientation":5,
   "structured":5,
   "active":7,
   "practical":8,
   "self-disclosure":1,
   "gender":"Female",
   "birth_year":1983,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District","Hayes Valley/Lower Haight/Duboce Triangle"],
       "therapies": ["Psychodynamic","Jungian Psychotherapy","Cognitive Behavioral Therapy","Interpersonal Therapy","Experiential Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)"]},

49:    {"name": "Laura Futransky",
       "solution-orientation":3,
   "structured":2,
   "active":6,
   "practical":9,
   "self-disclosure":2,
   "gender":"Female",
   "birth_year":1983,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Psychodynamic","Experiential Therapy","Acceptance And Commitment Therapy"],
       "days": ["Tuesday","Wednesday","Thursday"],
       "times": ["Mornings (7am - 11am)","Evening (5pm - 8pm)"]},

50:    {"name": "JS Very",
       "solution-orientation":5,
   "structured":5,
   "active":7,
   "practical":7,
   "self-disclosure":6,
   "gender":"Trans FTM",
   "birth_year":1982,
   "ethnicity":"White",
   "sexual_orientation":"Pansexual",
   "locations": ["Union Square/Mid-Market"],
       "therapies": ["Humanistic","Cognitive Behavioral Therapy","Mindfulness/Meditation"],
       "days": ["Wednesday","Thursday","Saturday (limited)"],
       "times": ["Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

51:    {"name": "Doug Ronning",
       "solution-orientation":6,
   "structured":7,
   "active":7,
   "practical":9,
   "self-disclosure":5,
   "gender":"Male",
   "birth_year":1962,
   "ethnicity":"White",
   "sexual_orientation":"Gay/lesbian",
   "locations": ["Noe Valley"],
       "therapies": ["Jungian Psychotherapy","Experiential Therapy","Mindfulness/Meditation"],
       "days": ["Monday","Tuesday"],
       "times": ["Afternoon (2pm - 5pm)"]},

52:    {"name": "Nicole O'Connor",
       "solution-orientation":4,
   "structured":3,
   "active":7,
   "practical":8,
   "self-disclosure":3,
   "gender":"Female",
   "birth_year":1972,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Noe Valley"],
       "therapies": ["Psychodynamic","Cognitive Behavioral Therapy","Interpersonal Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Tuesday","Thursday"],
       "times": ["Midday (11am - 2pm)"]},

53:    {"name": "Betty Michaud",
       "solution-orientation":3,
   "structured":3,
   "active":5,
   "practical":5,
   "self-disclosure":4,
   "gender":"Female",
   "birth_year":1971,
   "ethnicity":"Asian or Pacific Islander",
   "sexual_orientation":"Straight",
   "locations": ["Noe Valley"],
       "therapies": ["Humanistic","Interpersonal Therapy","Mindfulness/Meditation"],
       "days": ["Thursday"],
       "times": ["Afternoon (2pm - 5pm)"]},

54:    {"name": "Travis Robinson",
       "solution-orientation":7,
   "structured":7,
   "active":8,
   "practical":5,
   "self-disclosure":8,
   "gender":"Male",
   "birth_year":1972,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Marina/Cow Hollow"],
       "therapies": ["Humanistic","Experiential Therapy","Mindfulness/Meditation"],
       "days": ["Monday","Tuesday","Wednesday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

55:    {"name": "Julia Lehrman",
       "solution-orientation":8,
   "structured":7,
   "active":7,
   "practical":8,
   "self-disclosure":5,
   "gender":"Female",
   "birth_year":1986,
   "ethnicity":"White",
   "sexual_orientation":"Straight",
   "locations": ["Financial District","Union Square/Mid-Market","SoMa"],
       "therapies": ["Cognitive Behavioral Therapy","Mindfulness/Meditation","Coaching"],
       "days": ["Wednesday","Friday"],
       "times": ["Mornings (7am - 11am)","Midday (11am - 2pm)","Afternoon (2pm - 5pm)","Evening (5pm - 8pm)"]},

};

module.exports = providers;
